### ISSUE TITLE
bug with Big sur

### ISSUE THREAD

**Issue by shawkynasr** [planetoryd/redictionary#1]
When open app: 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: spawn EACCES
at _errnoException (util.js:1024:11)
at ChildProcess.spawn (internal/child_process.js:323:11)
at exports.spawn (child_process.js:514:9)
at exports.execFile (child_process.js:224:15)
at module.(anonymous function) (ELECTRON_ASAR.js:193:20)
at

**Comment by planetoryd** [comment]
Could you launch it in a terminal, and upload the output.

This issue is about the executable permissions of a file of the clipboard monitoring module inside the asar. It somehow works only for me.

You may also try `yarn run build` to see if it's the problem with travis

**Comment by planetoryd** [comment]
Also, use the newly published release

**Comment by shawkynasr** [comment]
I can't open .pacman extension

**Comment by planetoryd** [comment]
What distro are you using

**Comment by planetoryd** [comment]
Well that's macos. I'm not familiar with that

**Comment by shawkynasr** [comment]
Yes, That latest version of MacOS
